### ISSUE TITLE
Still Vue memory Issue from component framework

### ISSUE THREAD

**Issue by hank-cp** [ag-grid/ag-grid-vue#11]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Similar to #8 but problems from CellRenderer and CellEditor this time. Every components instantiated by `VueFrameworkFactory` will consume huge size of memory since Vue observes `GridApi` object in `params`.

**Expected behavior**
GH-10 has been submitted to fix this issue. Please kindly have a review on it.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-vue version:** 14.0.0
* **ag-Grid/ag-Grid-Enterprise version:** 14.0.0
* **VueJS version:** 2.1
* **Browser:** [all]
* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

This is tracked by AG-775

Since this can be tracked from our pipeline we are going to close this issue

https://www.ag-grid.com/ag-grid-pipeline/



===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months.

As a result, we don’t have capacity to take feature requests from GitHub.e

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
