### ISSUE TITLE
Grid will not display if Content Security Policy is missing 'unsafe-eval'

### ISSUE THREAD

**Issue by seanw** [ag-grid/ag-grid-vue#4]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The Vue component implementation uses a template function which will means it will fail in CSP environments that are missing 'unsafe-eval' for JavaScript. See:
https://vuejs.org/v2/guide/installation.html#CSP-environments

In Chrome, using ag-grid with Vue will give you these messages for the Content Security Policy equal to ""script-src 'self'" and the grid will not display:

> [Vue warn]: It seems you are using the standalone build of Vue.js in an environment with Content Security Policy that prohibits unsafe-eval. The template compiler cannot work in this environment. Consider relaxing the policy to allow unsafe-eval or pre-compiling your templates into render functions.
> 
> EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'
> 
> 
>  in
> with(this){return _c('div')}
> 
> found in
> 
> ---> \< AgGridVue \>
> 
> [Vue warn]: Error in mounted hook: "HierarchyRequestError: Failed to execute 'appendChild' on 'Node': This node type does not support this method."
> 
> found in
> 
> ---> \< AgGridVue \>
> 
> DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
>     at GridCore.init

The fix appears simple however. It seems you only need to replace the "template" function with a "render" function:
https://github.com/seanw/ag-grid-vue/commit/97daabbf00ddba69822999281f6f76def62760de

I've not tested this with the advanced features of ag-grid but this change makes the grid start up instead of displaying nothing.

**Expected behavior**

The grid should display without 'unsafe-eval'.

**Minimal reproduction of the problem with instructions**

Run ag-grid-vue within a page that has the CSP settings set to (sorry, don't know how to quickly set up a demo for this):
    Content Security Policy directive: "script-src 'self'

**What is the motivation / use case for changing the behavior?**

Security.

**Please tell us about your environment:**

Mac

* **ag-grid-vue version:**

12.0.0

* **ag-Grid version:**

12.0.2

* **VueJS version:**

2.4.2

* **Browser:**

Chrome

* **Language:**

TypeScript

**Comment by seanlandsman** [comment]
Thanks for reporting this - I'll make a note to pick this up next week

thanks

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-773 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

This is tracked by AG-773

Since this can be tracked from our pipeline we are going to close this issue

https://www.ag-grid.com/ag-grid-pipeline/



===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months.

As a result, we don’t have capacity to take feature requests from GitHub.e

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
