### ISSUE TITLE
RefreshInfiniteCache doesn't update row classes by getRowClass

### ISSUE THREAD

**Issue by badpunman** [ag-grid/ag-grid-vue#7]
This might be ag-grid issue and not ag-grid-vue related.

Using infinite row model with getRowClass gridoption, the RefreshInfiniteCache doesn't update row classes after the model changes. The class is only updated after the row is instantiated again.

**Comment by seanlandsman** [comment]
Hi,

Take a look at the docs here: https://www.ag-grid.com/javascript-grid-cell-styles/?framework=all#gsc.tab=0

Refresh of Styles

If you refresh a cell, or a cell is updated due to editing, the cellStyle, cellClass and cellClassRules are all applied again. This has the following effect:

cellStyle: All new styles are applied. If a new style is the same as an old style, the new style overwrites the old style.
cellClass: All new classes are applied. Old classes are not removed so be aware that classes will accumulate. If you want to remove old classes, then use cellClassRules.
cellClassRules: Rules that return true will have the class applied the second time. Rules tha return false will have the class removed second time.


In your case I'd use cellClassRules - this will probably do what you want it to do

thanks
